TypeError when the platform was not recognized
Script crashed because None on line 113 is not a String and cannot be used with os.path.join(str, str, str)

Suggest changing string to empty string or other 

Full error:
Your platform 'sunos5' is not being handled explicitly. It may work or not!
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    Path('native', 'embedded', '*.cpp')], platform=platform,
  File "REDACTED/jpype-master/setupext/platform.py", line 123, in Platform
    distutils.log.info("Add JNI directory %s" % os.path.join(java_home, 'include', jni_md_platform))
  File "REDACTED/lib/python3.6/posixpath.py", line 92, in join
    genericpath._check_arg_types('join', a, *p)
  File "REDACTED/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'